### ISSUE TITLE
Remove Hardcoded Values/Code

### ISSUE THREAD

**Issue by samgomena** [shared-systems/share_ui#26]
There's a lot of old hardcoded values on the master branch.

For instance, value for credits in the upper right hand corner of the dashboard, among other things.
I've also noticed some commented code in the jobs and resources files that was there for testing/setting up.

This code should be updated, pulled out, etc.

**Comment by lixphilosophy** [comment]
- set dashboard account machine situation initialize to 0.
- set available machine instance initialize to 0.
please notice if there is some endpoint opening for those value so I can bring the application fetch value through api.
